### ISSUE TITLE
AWS S3 buckets not being emptied before deletion

### ISSUE THREAD

**Issue by pogunshola** [CircleCI-Public/serverless-framework-orb#18]
**Orb Version**

1.0.1

**Describe the bug**

  When I package and deploy a project with the orb, once I try to do serverless remove --stage xyz for some reason I am given an error stating:

    An error occurred: ServerlessDeploymentBucket - The bucket you tried to delete is not empty (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; Request ID: ******; S3 Extended Request ID: ******; Proxy: null).
   
  My previous experience with using sls deploy on the command line has shown/lead me to believe that there's no need for me to make any sort of s3 configurations and have to manually remove the contents of the bucket because it will be done automatically. I've attached how my config file is setup.

From what I can tell it has something to do with the package or deploy part. I used the command line and not the orb to package and deploy and then used remove and it worked fine.

**To Reproduce**

From what i can tell doing what I did in the images below should replicate the issue

**Expected behavior**

I expect for the deployment to be removed without any issue like on CLI when i use the serverless remove --stage action 

**Additional context**

<img width="451" alt="Screen Shot 2021-10-07 at 2 24 21 PM" src="https://user-images.githubusercontent.com/92117392/136441500-c2ede57a-e4e9-471c-905d-ea92f5383cdf.png">
<img width="969" alt="Screen Shot 2021-10-07 at 2 24 08 PM" src="https://user-images.githubusercontent.com/92117392/136441531-1e52a5a9-086f-4007-ae31-17058e18f85a.png">
<img width="586" alt="Screen Shot 2021-10-07 at 2 24 38 PM" src="https://user-images.githubusercontent.com/92117392/136441554-2663d5b1-922d-48f6-9627-2efa172b30dc.png">

**Comment by KyleTryon** [comment]
Hey @pogunshola 
Sorry it took so long to get to this. I am doing a maintenance sweep now and taking a look. I am not an expert on the serverless framework, but it appears the behavior you are describing here is not a result of the orb, but a result of the behavior of the serverless CLI. Maybe we should work around this, but if this is an issue, it seems to me like something maybe the `serverless remove` command should be dealing with. I would recommend opening an issue with the serverless cli if this is still an issue for you.
