### ISSUE TITLE
Add parameter to specify serverless version

### ISSUE THREAD

**Issue by pholik** [CircleCI-Public/serverless-framework-orb#24]
**Is your feature request related to a problem? Please describe.**
It may not be always appropriate to use the latest version of serverless. 
Related to issue: #23 

**Describe the solution you'd like**
It might be useful have an option to specify version of serverless framework. Orb should provide a param to use fixed version of serverless.

**Comment by KyleTryon** [comment]
Added in #29

A new version of the orb will be published shortly, please keep an eye on the tags/releases later today or tomorrow.

**Comment by KyleTryon** [comment]
Hello,
Thank you all for reporting this issue. We have just released version 2.0.0 which should resolve this problem. Please try the latest version of the orb and let us know if you experience any issues.

https://github.com/CircleCI-Public/serverless-framework-orb/releases/tag/v2.0.0
https://circleci.com/developer/orbs/orb/circleci/serverless-framework
