### ISSUE TITLE
Skip or make the check of the provider credentials optional

### ISSUE THREAD

**Issue by ohjimijimijimi** [CircleCI-Public/serverless-framework-orb#26]
**Is your feature request related to a problem? Please describe.**

This orb [assumes](https://github.com/CircleCI-Public/serverless-framework-orb/blob/master/src/commands/setup.yml#L43-L48), when the provider selected is AWS, the credentials are set in the default AWS environment variables `AWS_ACCESS_KEY` and `AWS_SECRET_ACCESS_KEY`. In our pipelines, we don't use those envs and the setup step fails.

**Describe the solution you'd like**
Split the setup command into separate commands:
- `install`: install the serverless framework
- (optional) `auth`: authenticate to serverless.com. Options `app-name` and `org-name` should be moved to this command.
- (optional) `verify-provider`: verify the credentials for the specified provider. This command could have options. For example, if the provider is `AWS` we could specify the name of the env variables that have been used instead of the default ones or the AWS profile name to check.

**Describe alternatives you've considered**
The setup command could optionally skip the provider checks considering that the serverless framework has diverse ways to authorise an execution. For [AWS alone](https://www.serverless.com/framework/docs/providers/aws/guide/credentials) we can:
- use `serverless config credentials --provider aws --key <key> --secret <secret>`
- pass the profile inline with `--aws-profile <profile-name>`
- use the `profile` option of the `provider` configuration in the `serverless.yml` file. 
- using the `AWS_PROFILE` environment variable

**Additional context**
In general, adding more flexibility to this orb would make it far more usable.

**Comment by KyleTryon** [comment]
Removed in #32

New orb version will be published shortly.

**Comment by KyleTryon** [comment]
Hello,
Thank you all for reporting this issue. We have just released version 2.0.0 which should resolve this problem. Please try the latest version of the orb and let us know if you experience any issues.

https://github.com/CircleCI-Public/serverless-framework-orb/releases/tag/v2.0.0
https://circleci.com/developer/orbs/orb/circleci/serverless-framework
