### ISSUE TITLE
serverless-pseudo-parameters not installed.

### ISSUE THREAD

**Issue by sterling000** [CircleCI-Public/serverless-framework-orb#4]
1.0.1
https://app.circleci.com/pipelines/github/sterling000/deckmasterweb-serverless/9/workflows/beffe32c-c4bd-44b5-beac-dc37e0f71655

trying to figure out how to get passed this plugin install, it works locally, i can run serverless deploy and it functions properly, it's listed in the serverless.yml, i ran the serverless install plugin --name serverless-pseudo-parameters command locally and it ran fine. I've tried adding it to my config for the orb but i keep getting this error and not sure what to do next.

**To Reproduce**

1. Fork or Clone: https://github.com/sterling000/deckmasterweb-serverless
2. enable circleci for your repo
3. push a small change to trigger the pipeline.
4. observe in the deploy step, it fails to install the serverless-pseudo-parameters plugin after it installs the serverless-cli

**Expected behavior**

I started this project following the tutorial here: https://www.serverless.com/learn/tutorial/user-creation/
Then i attempted to add circleci CI/CD for it, so I followed the instructions here for this orb.
I just put the latest version numbers into the orb config because the example had errors with x.y etc.
I am still on step #17 User Creation of the tutorial. Everything functions fine locally, just trying to have it autodeploy for me when i submit to github. (I'll lock down the repo later once things are configured).

**Comment by mt-kelvintaywl** [comment]
@sterling000 looking at [where your Serverless config is (`{project_root}/services/user-service/serverless.yml`](https://github.com/sterling000/deckmasterweb-serverless/blob/master/services/user-service/serverless.yml), I think you'd need to explicitly inform the serverless `deploy` command where this file is located.
> typically, they [assume it is `{project_root}/serverless.yml`](https://www.serverless.com/framework/docs/providers/aws/guide/deploying/).

So in [this line of your CircleCI config](https://github.com/sterling000/deckmasterweb-serverless/blob/master/.circleci/config.yml#L12), you'd probably want to do this:

```diff
- command: serverless deploy -v
- command: serverless deploy -v --config services/user-service/serverless.yml
```
