### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by manuel-reil** [CircleCI-Public/serverless-framework-orb#40]
**Orb Version**
circleci/serverless-framework@2.0

**Describe the bug**
- The step "Install Serverless CLI" fails, after having worked for quite some time
- Last successful run was Dec 5th, 2022 - 8 days ago, no CircleCI changes since then

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/10340109/207352185-e52122ab-14ed-4a1c-9725-9be795b99e10.png">

**To Reproduce**

- Relevant Circle CI commands: 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/10340109/207352959-48b85567-3312-44fc-be1f-13ea0ea24f7e.png">

```
 steps:
      - attach_workspace:
          at: .
      - aws-cli/setup
      - serverless-framework/setup

      - run:
          name: Deploy
          command: |
            export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
            export EGRESS_QUEUENAME_PREFIX=$PROD_EGRESS_QUEUENAME_PREFIX
            sls deploy --stage prod
```

**Expected behavior**
- Should deploy as usual 

**Additional context**
-

**Comment by joaogoulart-vigil** [comment]
+1 same error, it started today

**Comment by GetOnMyLvl97** [comment]
+1

**Comment by springcoil** [comment]
👍

**Comment by Leonardocpn** [comment]
+1

**Comment by davidworkman9** [comment]
Just adding incase it helps narrow anything down. I had a successful run 8th of December.

**Comment by davidworkman9** [comment]
Serverless themselves have marked this as fixed, looks like there's a different URL they recommend to use now, https://slss.io/install.

Found here:
https://github.com/serverless/serverless/issues/11603
