### ISSUE TITLE
Serverless framework orb installation in circleCI

### ISSUE THREAD

**Issue by anish9461** [CircleCI-Public/serverless-framework-orb#7]
**1.0.1**
The version number of the orb

**Serverless framework orb installation error**
Hi, 
I am trying to integrate Serverless framework with circleCI. The installation works fine with using node as docker image and installing serverless framework. But, this is not working if I want to use the serverless framework orbs in circleCI to reduce build time. I get the following error (check attached file).

![circleCIError2](https://user-images.githubusercontent.com/13062244/90251995-ba03b380-de0c-11ea-9b03-84cf3949b162.PNG)

**Comment by gmemstr** [comment]
I expect this is because we install the framework then immediately attempt to use it, rather than taking time to install any defined plugins. Taking a deeper look.

**Comment by gmemstr** [comment]
@anish9461 I'm curious how the plugins are being defined, as there seems to be a handful of ways of doing it. Ultimately I think we might need some way of defining a command to install them - I can't see a way of doing this with the `serverless` command, but it appears plugins can be installed using npm?

**Comment by anish9461** [comment]
Hmm. So install serverless offline first using npm and then use the orb. right?

**Comment by KyleTryon** [comment]
Closing as issue appears to be abandoned.

**Comment by EddieEldridge** [comment]
I am having this issue also. I've tried installing the plugins globally with NPM first but it doesn't have any effect.
